import { Button, TextField } from "@mui/material";
import { Stack } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Styles from "../styles/Home.module.scss";

// Login and Intro page

const Home: NextPage = () => {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Movie Booking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Styles.main}>
        <div className={Styles.hero_img}>
          <Image src={"/hero.png"} width={"100%"} height={"100%"}></Image>
        </div>
        <div className={Styles.login_sec}>
          <h1>LoginSec</h1>
          <form action="">
            <Stack spacing={2}>
              <TextField
                type={"text"}
                variant={"outlined"}
                size={"small"}
                label={"Username"}
              />
              <TextField
                type={"password"}
                variant={"outlined"}
                size={"small"}
                label={"Password"}
              />
              <Button type={"submit"}>Login</Button>
            </Stack>
          </form>
          <Link href={"/home/mumbai"} passHref>
            Next
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
